config/routes.rb
Rails.application.routes.draw do
  get 'home',     to:'home#show',     as:'home'
  get 'about',    to:'about#show',    as:'about'
  get 'contact',  to:'contact#show',  as:'contact'

  root 'home#show'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/show.html.erb
<h1>About#show</h1>
<p>Find me in app/views/about/show.html.erb</p>

app/views/contact/show.html.erb
<h1>Contact#show</h1>
<p>Find me in app/views/contact/show.html.erb</p>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workshop</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <ul>
    <li><%= link_to 'Home', home_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
  </ul>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
</body>
</html>